Added JSDocs for all the existing functions
ubports/system-image-node-module pull request #15
Opened 2019-10-25 07:59 UTC by polo123qwe

2019-10-25 08:53 UTC, NeoTheThird requested changes
Wow, you are Awesome! Thank you so much!

One small change suggestion: `@returns {Promise}` might not be the most efficient way to document the return values, because what you're actually going to be interested in is what it resolves. The way i have seen this documented elsewhere would be like this:

```
/**
 * @async
 * @returns {Foo}
 * @throws {Bar}
 */
```

Where `Foo` is whatever you resolve and `Bar` whatever you reject. I'll be glad to hear your thoughts on this :)

2019-10-25 09:14 UTC, polo123qwe commented
From what I've read in the docs, @async should only be used if you are using the async declaration. e.g. async function foo() {}. It says it should not be used for callbacks or promises.

2019-10-26 11:41 UTC, NeoTheThird commented
I guess you're right, actually. It definitely works for now. So, thanks again for your PR and let's get this merged! Would you by any chance be interested in also doing this for [our adb/fastboot](https://github.com/ubports/promise-android-tools/issues/5) module? :)

2019-10-26 11:41 UTC, NeoTheThird approved these changes

2019-10-26 11:42 UTC, merged